SELECT TABLE_NAME, CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE R_CONSTRAINT_NAME IN (
  SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'APPUSERS' AND CONSTRAINT_TYPE = 'P'
)
ORDER BY TABLE_NAME;
EXIT;
