//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceApp
{
    public partial class Ledger
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.PlaceHolder phContract;
        protected global::System.Web.UI.WebControls.DropDownList ddlContract;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnGenerate;
        protected global::System.Web.UI.WebControls.Label lblLedgerMessage;
        protected global::System.Web.UI.WebControls.GridView gvLedger;
        protected global::System.Web.UI.WebControls.Panel pnlHolidayBadge;
        protected global::System.Web.UI.WebControls.Label lblHolidays;
        protected global::System.Web.UI.WebControls.Panel pnlGlobalAdjustBadge;
        protected global::System.Web.UI.WebControls.Label lblGlobalAdjust;
        protected global::System.Web.UI.WebControls.PlaceHolder phExportButtons;
    }
}
